### ISSUE TITLE
Make into separate sections

### ISSUE THREAD

**Issue by ghost** [Enegnei/JacobAppelbaumLeavesTor#15]
Maybe it be a good idea to separate the main sections like
- The History
- The Resignation
- The Website and Twitter Accounts
- The Allegations
- The Public Reaction

Would maybe make it easy to browse the document. I can send pull request if you like.

**Comment by Enegnei** [comment]
Can you be more specific? I have a table of contents at the top of the document with those sections hyperlinked, and their headers are second-largest in size. (## The History etc).

**Comment by ghost** [comment]
Yes. The table of contents is all linking to sections (## The History) on the same file or page. If split into separate files (The-History.md) it would make separate pages that could better make for a markdown  website or like chapters in an eBook.

**Comment by Enegnei** [comment]
Ah, I see. As with https://github.com/Enegnei/JacobAppelbaumLeavesTor/issues/16 I'm going to reference https://github.com/Enegnei/JacobAppelbaumLeavesTor/issues/10, which talks about how I was planning to create a GitBook repository (which would automatically create downloadable formats as well) for people who wanted better navigation. I'm still willing to do that but I didn't get any responses to the idea. A chapter format in GitBook looks cleaner than it would here with multiple .md files.

**Comment by ghost** [comment]
I see comment about gitbook. I have never seen gitbook before but assume it is similar to ebooks. My idea is that maybe separate areas is helpful. Or maybe timeline of important events make things more clear than book format. Lots of details here and peoples brains not best at cross comparing things. Maybe make sense?

**Comment by Enegnei** [comment]
Yes, it downloads in PDF, Mobi, and ePub formats as far as I know. Here is an example of the online format https://towcenter.gitbooks.io/guide-to-journalism-and-design/content/. There are two text fonts & sizes, along with sepia and night modes.

The timeline would have to be on a separate page as well. In an eBook format it should probably go in the appendix.
