### ISSUE TITLE
Second and more revealing Anna Loll piece

### ISSUE THREAD

**Issue by ghost** [Enegnei/JacobAppelbaumLeavesTor#18]
http://www.taz.de/Der-Fall-Jacob-Appelbaum/!5361578/

Published 10. Dezember 2016

**Comment by Enegnei** [comment]
I think I've referenced that one already under https://github.com/Enegnei/JacobAppelbaumLeavesTor/blob/master/JacobAppelbaumLeavesTor.md#isis-lovecruft but I will find a place to add attribution links to Loll and Kaul since it doesn't appear I've done that anywhere.

**Comment by ghost** [comment]
Thanks! I see now that it was referenced. Thanks for making it more discoverable.
-- David
