### ISSUE TITLE
Just FYI

### ISSUE THREAD

**Issue by adrienne** [Enegnei/JacobAppelbaumLeavesTor#2]
Violet Blue has some tweets about this https://twitter.com/violetblue/status/740445576643383296 (and https://twitter.com/violetblue/ in general)

**Comment by Enegnei** [comment]
Added. Thanks! If you happen to know where I could get more information on the plagiarism allegations other than https://web.archive.org/web/20160605152831/http://comments.gmane.org/gmane.comp.security.otr.devel/1546, let me know. I haven't seen anyone offer specifics yet.

**Comment by adrienne** [comment]
I don't, I'm sorry. I know Meredith Patterson and her spouse were directly affected; Quinn Norton might also know details? But I haven't seen anything particularly useful being posted.

**Comment by adrienne** [comment]
There is this tweet from 2013 (which would have been well AFTER Sassaman's suicide, and well before the current round of horrors): https://twitter.com/travisgoodspeed/status/302231453670977536

**Comment by Enegnei** [comment]
Yes, that's the conversation I'd found dated around the same time (mid-Feb 2013) as https://web.archive.org/web/20160605152831/http://comments.gmane.org/gmane.comp.security.otr.devel/1546. If I'm not mistaken that one looks like it ruled in Appelbaum's favour, not Nadim's. Norton has only said this https://archive.is/5Sywt so far. I'm just surprised more people haven't written about it in more detail if it was so prolific, reason being that it's much easier to document as evidence than the other allegations at the moment.
