### ISSUE TITLE
Certain links do not work anymore

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [Enegnei/JacobAppelbaumLeavesTor#22]
> Tor developer George Kadianakis ("asn") shared a link with former Tor Browser bundle signer Erinn Clark ("helix") to a Riseup.net etherpad first saved on November 30th, 2015 (shown via the timeslider), which doesn't appear to have been edited further until June 26th 2016; someone used the pad to allege that Lovecruft was an FBI informant between 14:36-14:49 on June 27th. Since anyone can edit anonymously and the date of the edit is so recent (within a day of the pastebins going viral), there is no reason to believe this etherpad document is authentic.

The etherpad link in this quote do not work anymore. Same goes for the githubusercontent link under it.

**Comment by Enegnei** [comment]
Thanks! I have fixed the broken image link to an archived copy, and added a note about the etherpad links being useless now. The etherpad was not an important source anyway. https://github.com/Enegnei/JacobAppelbaumLeavesTor/commit/f9848527680214523d33fd7bb40fa9bb4a75d0ca
