### ISSUE TITLE
I hope i'm not annoying you with this but here's another tweet:

### ISSUE THREAD

**Issue by adrienne** [Enegnei/JacobAppelbaumLeavesTor#5]
https://twitter.com/asta_fish/status/743165546238189568

(In context it's clearly about Appelbaum. Dunno if you want to include it or not, but it IS another (pseudonymously, but NOT anonymously) reported incident.)

**Comment by Enegnei** [comment]
I was actually just in the process of adding those, along with other things, when you commented. No, it's not annoying at all; I appreciate how many people are looking out for relevant information and then sharing it with me, so no worries!

**Comment by adrienne** [comment]
Also a longer statement by Violet Blue: https://medium.com/@violetblue/but-he-does-good-work-6710df9d9029

**Comment by Enegnei** [comment]
Added. There are at least two mistakes/ confusions in it that I noted as well.
