### ISSUE TITLE
Just another link

### ISSUE THREAD

**Issue by LuciousLisa** [Enegnei/JacobAppelbaumLeavesTor#7]
Just ICYMI - Gabriella Coleman's (@BiellaColeman) response.
https://thecryptosphere.com/2016/06/24/tyranny-of-structurelessness/

**Comment by Enegnei** [comment]
Added: https://github.com/Enegnei/JacobAppelbaumLeavesTor/commit/bd58fd1144258e9e44e20e1567f40698ad9981a8
